
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - muhammad-sammy.csharp
    - christian-kohler.path-intellisense
    - ms-dotnettools.vscode-dotnet-runtime
    - github.vscode-github-actions
    - josefpihrt-vscode.roslynator
    - redhat.vscode-xml
    - DotJoshJohnson.xml
    - esbenp.prettier-vscode
    - PrateekMahendrakar.prettyxml
